# Generated by Django 3.2.25 on 2024-10-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0004_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image1',
            field=models.ImageField(upload_to='review_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, upload_to='review_pics'),
        ),
    ]
